

#if ! defined __DVRS_API_H_
#define __DVRS_API_H_
#include "datatype.h"

#ifdef __cplusplus
extern "C" {
#endif

#if ! defined DWORD
#define DWORD  ULONG
#endif
#if ! defined WORD
#define WORD   USHORT
#endif
#if ! defined BYTE
#define BYTE   UCHAR
#endif


#define MAX_BUFFER_NUM  2
#define MAX_AUIDO_BUFFER_NUM   6 
#define AUDIO_PACK_BUFFER  640 
	/*
结构名称：TDrvParam

*/
typedef struct tagTShareMem
{
    DWORD dwDmaRun;
}TShareMem,*PTShareMem;
typedef struct tagTVideoParam
{
	BYTE   nSubNum;
    BYTE   Brightness;
	BYTE   Contrast;
	BYTE   Saturation;
	BYTE   Hue;
} TVideoParam, * PVideoParam;

typedef struct tagTVIDEO_CODE_INFO
{
	int   nSubNum;
	int   nWidth;
	int   nHeight;
	int   nFrameRate;

} TVIDEO_CODE_INFO, * PTVIDEO_CODE_INFO;

/*
结构名称：TDrvParam

*/
typedef struct tagDrvParam
{
	DWORD   dwAddress;
	DWORD   dwValue;
	DWORD   dwFlags;
} TDrvParam, * PDrvParam;
/*
结构名称：TPCICARDINFO
用于取得pci的信息。
*/
typedef struct tagTPCICARDINFO
{
    WORD   dwVendorID;
    WORD   dwDeviceID;
    WORD   dwBusNumber;
    WORD   dwFunctionNumber;
    WORD   dwDeviceNumber;
} TPCICARDINFO,*LPTPCICARDINFO;
/*
结构名称：DATA_BUFFER_ITEM
用于传送数据的数据信息的结构
*/
typedef struct tagDSDrvParam
{
	DWORD   dwAddress;
	DWORD   dwValue;
	DWORD   dwSubNum;
	DWORD   dwIndex;
	DWORD   dwFlogs;
} TMemParam, * PDMemParam;

typedef struct
{
	DWORD dwHandle;
	DWORD dwIsVideo;
    DWORD dwSize;
	DWORD  dwUserAddress;
	DWORD  dwStatusAddress;
} TMemStruct, * PMemStruct;




typedef struct tagDATA_BUFFER_MSG
{
	DWORD dwHandle;
	/////////////////////////
	BOOL m_bVideo;
	int    nSubNum;
	BYTE   nEvenOrOdd;  // 0x00 even  0x01 odd
	unsigned short    nWidth;
	unsigned short    nHeight;
	unsigned short    nPatch;
	///////////////////////
	unsigned short     nSize;
	void   *pDataBuffer;
	LPBYTE pBuffer;
}DATA_BUFFER_MSG,*LPDATA_BUFFER_MSG;

typedef struct tagDATA_BUF_HEAD
{
	int nDspIndex;
	int nSplitIndex;    
}DATA_BUF_HEAD,*LPDATA_BUF_HEAD;


#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) )

#define METHOD_BUFFERED                 0
#define METHOD_IN_DIRECT                1
#define METHOD_OUT_DIRECT               2
#define METHOD_NEITHER                  3

#define FILE_ANY_ACCESS                 0
#define FILE_READ_ACCESS          ( 0x0001 )    // file & pipe
#define FILE_WRITE_ACCESS         ( 0x0002 )    // file & pipe


#define FILE_DEVICE_DVRS_API 0x8D00
#define DVRS_CTRL_BASE          0xA00

/*
//用于测试 
*/
#define IOCTL_DVRS_TEST \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 1), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
/*
//取得pci的信息
*/
#define IOCTL_DVRS_GETPCIINFO  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 2), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_REGISTER_EVENT  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 3), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_UNREGISTER_EVENT  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 4), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_SET_SUBCHANNELNUM  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 5), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_DVRS_START_CAPTURE  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 6), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_DVRS_STOP_CAPTURE  \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 7), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_SET_VIDEO_PARA \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 8), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_DVRS_GET_VIDEO_PARA \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 9), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

/*
//用于设置数据缓冲
*/
#define IOCTL_DVRS_SET_VIDEO_DATA_BUFFER \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 10), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_VIDEO_DATA_BUFFER \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 11), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_SET_VIDEO_STANDARD \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 12), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_VIDEO_STANDARD \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 13), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_SET_VIDEO_PICTURE_FORMAT \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 14), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_VIDEO_PICTURE_FORMAT \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 15), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_SET_COLOR_FORMAT_1 \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 16), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_COLOR_FORMAT_1 \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 17), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_SET_COLOR_FORMAT_2 \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 18), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_COLOR_FORMAT_2 \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 19), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_STOP_DSP \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 20), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_START_DSP \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 21), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_MAP_DATA_BUFFER \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 22), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_UNMAP_DATA_BUFFER \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 23), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_DVRS_GET_FRAME_RATE \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 24), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_SET_FRAME_RATE \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 25), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_DVRS_SET_DSP_INDEX \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 26), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_GET_VIDEO_CODE_INFO \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 27), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_REG_WRITE \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 28), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_REG_READ \
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 29), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_MAP_SHARE_MEM\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 30), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_UNMAP_SHARE_MEM\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 31), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_SET_HD1_SIZE\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 32), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_SET_VOLUME\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 33), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_SET_SHARPNESS\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 34), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_DVRS_CTRL_VIDEO_CHANGE\
    CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 35), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_AUT\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 36), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_SET_MAX_FRAME\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 37), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_I2C_INIT\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 38), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_I2C_WRITE\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 39), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_I2C_READ\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 40), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_CPUMON\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 41), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_UNCPUMON\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 42), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_START_DMA\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 43), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_STOP_DMA\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 44), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_CHECK_RUN\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 45), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_START_RUN\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 46), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_READ_ZONE\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 47), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_WRITE_ZONE\
	CTL_CODE(FILE_DEVICE_DVRS_API, (DVRS_CTRL_BASE + 48), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#ifdef __cplusplus
}
#endif

#endif